"""Добавлено поле депозит в таблицу Table

Revision ID: 57de6cfb8fd6
Revises: fcdecc81bd6c
Create Date: 2025-05-11 04:41:17.737281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57de6cfb8fd6'
down_revision = 'fcdecc81bd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_tables')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('deposit')

    op.create_table('photo_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='photo_tables_pkey')
    )
    # ### end Alembic commands ###
