"""Удалили PhotoTable, добавили поле photo в Table

Revision ID: a8e2fde3cacb
Revises: ba5d7054ee5c
Create Date: 2025-05-11 04:08:01.114667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e2fde3cacb'
down_revision = 'ba5d7054ee5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_tables', schema=None) as batch_op:
        batch_op.drop_constraint('photo_tables_id_table_fkey', type_='foreignkey')
        batch_op.drop_column('id_table')

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('photo_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_table', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('photo_tables_id_table_fkey', 'tables', ['id_table'], ['id'])

    # ### end Alembic commands ###
