"""Добавлено поле capacity в таблицу Table

Revision ID: fcdecc81bd6c
Revises: a8e2fde3cacb
Create Date: 2025-05-11 04:13:51.300480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdecc81bd6c'
down_revision = 'a8e2fde3cacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
